#!/system/bin/sh

(
if grep torrented /proc/version > /dev/null
then
   echo "** torrented's boot configuration:"
   for script in /system/etc/torrented/*
   do
$script
   done
else
   echo "!! torrented's boot configuration not running, this isn't my kernel !!"
fi
)2>&1 | tee /sdcard/torrented.log
